if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "embed-spirv.cmake requires INPUT and OUTPUT")
endif()
if(NOT DEFINED SYMBOL)
  set(SYMBOL rgb_to_yuv_422_spv)
endif()

file(READ "${INPUT}" SPIRV_HEX HEX)
string(LENGTH "${SPIRV_HEX}" HEX_LENGTH)
math(EXPR REMAINDER "${HEX_LENGTH} % 8")
if(NOT REMAINDER EQUAL 0)
  message(FATAL_ERROR "SPIR-V input is not a whole number of 32-bit words")
endif()
math(EXPR WORD_COUNT "${HEX_LENGTH} / 8")
set(WORDS "")
if(WORD_COUNT GREATER 0)
  math(EXPR LAST_WORD "${WORD_COUNT} - 1")
  foreach(INDEX RANGE 0 ${LAST_WORD})
    math(EXPR POSITION "${INDEX} * 8")
    string(SUBSTRING "${SPIRV_HEX}" ${POSITION} 2 B0)
    math(EXPR POSITION_1 "${POSITION} + 2")
    math(EXPR POSITION_2 "${POSITION} + 4")
    math(EXPR POSITION_3 "${POSITION} + 6")
    string(SUBSTRING "${SPIRV_HEX}" ${POSITION_1} 2 B1)
    string(SUBSTRING "${SPIRV_HEX}" ${POSITION_2} 2 B2)
    string(SUBSTRING "${SPIRV_HEX}" ${POSITION_3} 2 B3)
    string(APPEND WORDS "0x${B3}${B2}${B1}${B0}U,")
    math(EXPR COLUMN "${INDEX} % 8")
    if(COLUMN EQUAL 7)
      string(APPEND WORDS "\n")
    endif()
  endforeach()
endif()

file(WRITE "${OUTPUT}" "#pragma once\n#include <array>\n#include <cstdint>\nnamespace mcraw::generated {\ninline constexpr std::array<std::uint32_t, ${WORD_COUNT}> ${SYMBOL}{{\n${WORDS}\n}};\n}\n")
